apiVersion: v1
kind: Namespace
metadata:
  name: nilelink-production
  labels:
    name: nilelink-production
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: nilelink-staging
  labels:
    name: nilelink-staging
    environment: staging
