name = "nilelink-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "nilelink_ledger"
database_id = "8ef5c10d-c7f7-45a6-8478-85a6fa3176b9"

[vars]
ENVIRONMENT = "production"
VERSION = "1.0.0"
